{{- if and .Values.rule.enabled .Values.rule.ingress.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "thanos.rule.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.rule.labels" . | nindent 4 }}
    prometheus.io/service-monitor: "false"
  {{- with .Values.rule.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.grpcPort }}
      targetPort: grpc
    - name: http
      protocol: TCP
      port: {{ .Values.httpPort }}
      targetPort: http
  selector:
    {{- include "thanos.rule.selectorLabels" . | nindent 4 }}
{{- end -}}
