{{- if .Values.rule.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "thanos.rule.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.rule.labels" . | nindent 4 }}
  {{- with .Values.rule.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc
      port: {{ .Values.grpcPort }}
      targetPort: grpc
    - name: http
      protocol: TCP
      port: {{ .Values.httpPort }}
      targetPort: http
  selector:
    {{- include "thanos.rule.selectorLabels" . | nindent 4 }}
{{- end -}}
