{{- if .Values.receive.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "thanos.receive.ingestor.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.receive.ingestor.labels" . | nindent 4 }}
  {{- with .Values.receive.ingestor.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc
      port: {{ .Values.grpcPort }}
      targetPort: grpc
    - name: http
      protocol: TCP
      port: {{ .Values.httpPort }}
      targetPort: http
    - name: http-rem-write
      protocol: TCP
      port: {{ .Values.httpRemoteWritePort }}
      targetPort: http-rem-write
  selector:
    {{- include "thanos.receive.ingestor.selectorLabels" . | nindent 4 }}
{{- end -}}
